<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Custom suite" duration-ms="50" started-at="2018-09-17T08:20:59Z" finished-at="2018-09-17T08:20:59Z">
    <groups>
      <group name="failure-test">
        <method signature="EmployeeServiceImplTest.testGenerateBasicSalaryFailure()[pri:0, instance:com.test.ng.EmployeeServiceImplTest@445b84c0]" name="testGenerateBasicSalaryFailure" class="com.test.ng.EmployeeServiceImplTest"/>
        <method signature="EmployeeServiceImplTest.testGenerateBasicSalaryGeneratedException()[pri:0, instance:com.test.ng.EmployeeServiceImplTest@445b84c0]" name="testGenerateBasicSalaryGeneratedException" class="com.test.ng.EmployeeServiceImplTest"/>
      </group> <!-- failure-test -->
    </groups>
    <test name="TestNGDemo" duration-ms="50" started-at="2018-09-17T08:20:59Z" finished-at="2018-09-17T08:20:59Z">
      <class name="com.test.ng.EmployeeServiceImplTest">
        <test-method status="PASS" signature="testGenerateBasicSalaryFailure()[pri:0, instance:com.test.ng.EmployeeServiceImplTest@445b84c0]" name="testGenerateBasicSalaryFailure" duration-ms="30" started-at="2018-09-17T13:50:59Z" finished-at="2018-09-17T13:50:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGenerateBasicSalaryFailure -->
        <test-method status="FAIL" signature="testGenerateBasicSalaryGeneratedException()[pri:0, instance:com.test.ng.EmployeeServiceImplTest@445b84c0]" name="testGenerateBasicSalaryGeneratedException" duration-ms="1" started-at="2018-09-17T13:50:59Z" finished-at="2018-09-17T13:50:59Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception java.lang.Exception but got org.testng.TestException: 
The exception was thrown with the wrong message: expected "Employee working details canno" but got "Employee working details cannot be null"]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception java.lang.Exception but got org.testng.TestException: 
The exception was thrown with the wrong message: expected "Employee working details canno" but got "Employee working details cannot be null"
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.testng.TestException: 
The exception was thrown with the wrong message: expected "Employee working details canno" but got "Employee working details cannot be null"
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1481)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 22 more
Caused by: java.lang.Exception: Employee working details cannot be null
	at com.test.ng.service.impl.EmployeeServiceImpl.generateBasicSalary(EmployeeServiceImpl.java:28)
	at com.test.ng.EmployeeServiceImplTest.testGenerateBasicSalaryGeneratedException(EmployeeServiceImplTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGenerateBasicSalaryGeneratedException -->
      </class> <!-- com.test.ng.EmployeeServiceImplTest -->
    </test> <!-- TestNGDemo -->
  </suite> <!-- Custom suite -->
</testng-results>
